os: Visual Studio 2017

version: 1.0.2.{build}

configuration:
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

environment:
  COVERALLS_REPO_TOKEN:
    secure: pXizcjLI1WirF6HJk1v46ImkEerH5y1EfXB/rpDzojJjMVIxuyLJcgisUeIXH256

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe'
  - cmd: dotnet-1.1.1-sdk-win-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- dotnet restore .\src\NETStandard.HttpListener -v Minimal
- dotnet restore .\src\TestConsoleApp -v Minimal
# - nuget restore .\src\TestApp\TestApp.csproj -PackagesDirectory packages
- dotnet restore .\test\NETStandard.HttpListener.Tests -v Minimal

- dotnet build .\src\NETStandard.HttpListener\NETStandard.HttpListener.csproj -c %CONFIGURATION%
- dotnet build .\src\TestConsoleApp\TestConsoleApp.csproj -c %CONFIGURATION%
- dotnet build .\test\NETStandard.HttpListener.Tests\NETStandard.HttpListener.Tests.csproj -c %CONFIGURATION%
#- cmd: msbuild .\src\TestApp\TestApp.csproj /p:Configuration=%CONFIGURATION% /p:Platform=x86

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\test\NETStandard.HttpListener.Tests

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -target:dotnet.exe -targetargs:"test test\NETStandard.HttpListener.Tests\NETStandard.HttpListener.Tests.csproj --configuration %CONFIGURATION%  --no-build" -output:coverage.xml -register:user -filter:"+[NETStandard.HttpListener]* -[NETStandard.HttpListener.Tests]*" -returntargetcode -register:user -oldstyle'
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml

artifacts:
- path: artifacts\**\*.*

cache:
- packages